grpc:
  server:
    port: 8810
    max-inbound-message-size: 9155241000

spring:
  application:
    name: rococo-painting
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    generate-ddl: true
    open-in-view: false
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.boot.autoconfigure: INFO
    net.devh.boot.grpc: INFO

---
spring:
  config:
    activate:
      on-profile: 'local'
  datasource:
    url: 'jdbc:mysql://localhost:3306/rococo-painting?serverTimezone=UTC&createDatabaseIfNotExist=true'
grpc:
  client:
    grpcMuseumClient:
      address: 'static://localhost:8806'
      negotiationType: PLAINTEXT

    grpcCountriesClient:
      address: 'static://localhost:8806'
      negotiationType: PLAINTEXT

    grpcArtistClient:
      address: 'static://localhost:8808'
      negotiationType: PLAINTEXT
---
spring:
  config:
    activate:
      on-profile: 'docker'
  datasource:
    url: 'jdbc:mysql://rococo-db:3306/rococo-painting?serverTimezone=UTC&createDatabaseIfNotExist=true'

grpc:
  client:
    grpcMuseumClient:
      address: 'static://museum.rococo.dc:8806'
      negotiationType: PLAINTEXT

    grpcCountriesClient:
      address: 'static://museum.rococo.dc:8806'
      negotiationType: PLAINTEXT

    grpcArtistClient:
      address: 'static://artist.rococo.dc:8808'
      negotiationType: PLAINTEXT

---
